/********************************************************************/
/****************  Name     : Mohamed Adel Ramadan  *****************/
/****************  Date     : 6/1/2021              *****************/
/****************  Version  : 1.0v                  *****************/
/****************  SWC      : Stepper Motor         *****************/    
/********************************************************************/


#include  "DATA_TYPE.h"
#include  "BIT_MATH.h"

#include  "STEPPER_MOTOR_private.h"
#include  "STEPPER_MOTOR_config.h"
#include  "STEPPER_MOTOR_interfac.h"

void STEPPER_MOTOR_voiddrive(u16 copy_u16degree,u8 copy_u8direction)
{
  u8 local_u8nof_iteration,i,local_u8nof_step;
  
  local_u8nof_step =  (copy_u16degree * MAX_ITERATION)/(MAX_ITERATION);
 
  local_u8nof_iteration = local_u8nof_step/4;
  if(STEPER_MOTOR_PIN_COM == VCC)
  {
  if(copy_u8direction == CLOCK_WISE )
  {
	 for(i=0;i<local_u8nof_iteration;i++)
	 {		 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_LOW);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_HIGH); 
	_delay_ms(10);
	
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_HIGH);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_HIGH);
    _delay_ms(10);
	
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_HIGH);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_LOw); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_HIGH);
    _delay_ms(10);
	
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_HIGH);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_LOW);  	
	_delay_ms(10);
	
	 }
  }
  else if((copy_u8direction == COUNTER_CLOCK_WISE)
  {
 for(i=0;i<local_u8nof_iteration;i++)
	 {  
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_HIGH);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_LOW);
    _delay_ms(10);	
	
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_HIGH);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_HIGH);
    _delay_ms(10);
	
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_HIGH);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_HIGH);
    _delay_ms(10);
	
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_LOW);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_HIGH); 
    _delay_ms(10);
	
  }
  }
  
  
}
else if (STEPER_MOTOR_PIN_COM ==GROUND)
{
if(copy_u8direction == CLOCK_WISE )
  {
	 for(i=0;i<local_u8nof_iteration;i++)
	 {		 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_HIGH);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_LOW); 
	_delay_ms(10);
	
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_LOW);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_LOW);
    _delay_ms(10);
	
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_LOW);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_LOW);
    _delay_ms(10);
	
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_LOW);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_HIGH);  	
	_delay_ms(10);
	
	 }
  }
  else if((copy_u8direction == COUNTER_CLOCK_WISE)
  {
 for(i=0;i<local_u8nof_iteration;i++)
	 {  
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_LOW);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_HIGH);
    _delay_ms(10);	
	
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_LOW);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_LOW);
    _delay_ms(10);
	
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_LOW);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_HIGH); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_LOW);
    _delay_ms(10);
	
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR1,STEPER_MOTOR_PIN_TR1,DIO_U8_HIGH);
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR2,STEPER_MOTOR_PIN_TR2,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR3,STEPER_MOTOR_PIN_TR3,DIO_U8_LOW); 
	DIO_u8SetPinValue(STEPPER_MOTOR_PORT_PIN_TR4,STEPER_MOTOR_PIN_TR4,DIO_U8_LOW); 
    _delay_ms(10);
	
  
  }
  
  
}
	
	
}
}








