/********************************************************************/
/****************  Name     : Mohamed Adel Ramadan  *****************/
/****************  Date     : 6/1/2021              *****************/
/****************  Version  : 1.0v                  *****************/
/****************  SWC      : DIO                   *****************/    
/********************************************************************/

/*options : 1- DIO_u8_INTIAL_OUTPUT
 *           2- DIO_u8_INTIAL_INPUT
 */
#ifndef DIO_CONFIG_H
#define DIO_CONFIG_H

#define  DIO_u8_PA0_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PA1_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PA2_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PA3_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PA4_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PA5_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PA6_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PA7_DIRECTION    DIO_u8_INTIAL_INPUT

#define  DIO_u8_PB0_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PB1_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PB2_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PB3_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PB4_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PB5_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PB6_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PB7_DIRECTION    DIO_u8_INTIAL_INPUT

#define  DIO_u8_PC0_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PC1_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PC2_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PC3_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PC4_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PC5_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PC6_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PC7_DIRECTION    DIO_u8_INTIAL_INPUT

#define  DIO_u8_PD0_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PD1_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PD2_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PD3_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PD4_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PD5_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PD6_DIRECTION    DIO_u8_INTIAL_INPUT
#define  DIO_u8_PD7_DIRECTION    DIO_u8_INTIAL_INPUT

/* options : 1- DIO_u8_OUTPUT_HIGH
 *           2- DIO_u8_OUTPUT_LOW
 *           3- DIO_u8_INPUT_FLOATING
 *           4- DIO_u8_INPUT_PULUP
 */


#define  DIO_u8_PA0_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PA1_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PA2_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PA3_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PA4_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PA5_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PA6_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PA7_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING

#define  DIO_u8_PB0_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PB1_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PB2_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PB3_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PB4_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PB5_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PB6_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PB7_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING

#define  DIO_u8_PC0_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PC1_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PC2_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PC3_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PC4_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PC5_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PC6_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PC7_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING

#define  DIO_u8_PD0_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PD1_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PD2_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PD3_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PD4_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PD5_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PD6_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING
#define  DIO_u8_PD7_INITTIAL_VALUE    DIO_u8_INPUT_FLOATING

#endif
